version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  server:
    build:
        context: . #改为了根目录，本来是 ./server
        dockerfile: server/Dockerfile # 新增了该条命令用来指定 server 目录下的 Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: todolist
      JWT_SECRET: your_jwt_secret
    ports:
      - "50051:50051"
    depends_on:
      - mysql
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  grpc-web:
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge